name: Deploy release tags to test environment
# This only deploy release to none production environments
# Production will be pushed to config repository on release and a merge request is needed in release repository

on:
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        required: true
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set selected color
        run: echo ${{github.event.inputs.environment}}
